spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/vigiafiscal
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

notification:
  mock: false
  email:
    remetente: noreply@vigiafiscal.com.br
  whatsapp:
    phone-number-id: ${META_WHATSAPP_PHONE_NUMBER_ID}
    access-token: ${META_WHATSAPP_ACCESS_TOKEN}

cors:
  allowed-origins: "https://vigiafiscal.com.br,https://www.vigiafiscal.com.br"

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  success-url: https://vigiafiscal.com.br/assinatura?checkout=success
  cancel-url: https://vigiafiscal.com.br/assinatura?checkout=cancel
  price-id:
    basico: price_1TOMauFOYK0cL4qsikZZANsn
    pro: price_1TOMaqFOYK0cL4qsM8tPr5TM
    enterprise: price_1TOMauFOYK0cL4qsLD0to2Ex

springdoc:
  swagger-ui:
    enabled: false

sefaz:
  url:
    distribuicao: https://www.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx
  ambiente: ${SEFAZ_AMBIENTE}
  cnpj:
    autorizador: ""

management:
  health:
    mail:
      enabled: false